// File: data/entity/ExpenseEntity.kt
package com.happysappy.app.data.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Room Entity representing an expense record in the database.
 * 
 * This entity stores all information about a single expense entry,
 * including amount, category, date, frequency, and optional notes.
 */
@Entity(tableName = "expenses")
data class ExpenseEntity(
    /**
     * Unique identifier for the expense.
     * Auto-generated by Room database.
     */
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0L,
    
    /**
     * The amount of money spent.
     * Must be a positive value.
     */
    val amountSpent: Double,
    
    /**
     * Category of the expense.
     * Common categories: Food, Transport, Shopping, Entertainment, 
     * Bills, Health, Education, Other
     */
    val category: String,
    
    /**
     * Timestamp of when the expense occurred.
     * Stored as milliseconds since epoch.
     */
    val date: Long,
    
    /**
     * Frequency of this expense occurrence.
     * Must be one of the following exact values:
     * - "Daily"
     * - "Weekly"
     * - "Monthly"
     * - "Quarterly"
     * - "Annually"
     */
    val frequency: String,
    
    /**
     * Optional note or description for the expense.
     * Can be null if no note is provided.
     */
    val note: String? = null
) {
    companion object {
        // Valid frequency values as constants
        const val FREQUENCY_DAILY = "Daily"
        const val FREQUENCY_WEEKLY = "Weekly"
        const val FREQUENCY_MONTHLY = "Monthly"
        const val FREQUENCY_QUARTERLY = "Quarterly"
        const val FREQUENCY_ANNUALLY = "Annually"
        
        // Valid frequencies list for validation
        val VALID_FREQUENCIES = listOf(
            FREQUENCY_DAILY,
            FREQUENCY_WEEKLY,
            FREQUENCY_MONTHLY,
            FREQUENCY_QUARTERLY,
            FREQUENCY_ANNUALLY
        )
        
        /**
         * Validates if the given frequency is valid.
         * @param frequency The frequency string to validate
         * @return true if valid, false otherwise
         */
        fun isValidFrequency(frequency: String): Boolean {
            return VALID_FREQUENCIES.contains(frequency)
        }
        
        /**
         * Gets the frequency in milliseconds for scheduling purposes.
         * @param frequency The frequency string
         * @return The interval in milliseconds
         */
        fun getFrequencyInMillis(frequency: String): Long {
            return when (frequency) {
                FREQUENCY_DAILY -> 24 * 60 * 60 * 1000L // 1 day
                FREQUENCY_WEEKLY -> 7 * 24 * 60 * 60 * 1000L // 7 days
                FREQUENCY_MONTHLY -> 30 * 24 * 60 * 60 * 1000L // 30 days (approximate)
                FREQUENCY_QUARTERLY -> 90 * 24 * 60 * 60 * 1000L // 90 days (approximate)
                FREQUENCY_ANNUALLY -> 365 * 24 * 60 * 60 * 1000L // 365 days
                else -> 24 * 60 * 60 * 1000L // Default to daily
            }
        }
    }
    
    /**
     * Formats the amount as currency string.
     * @return Formatted currency string (e.g., "$50.00")
     */
    fun getFormattedAmount(): String {
        return String.format("$%.2f", amountSpent)
    }
}